- name: Backend setup
  hosts: all
  become: yes
  tasks: 
    - name: Disbale nodejs default version
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Enable nodejs 18 version
      ansible.builtin.shell: dnf module enable nodejs:18 -y
    
    - name: Install nodejs
      ansible.builtin.dnf:
       name: nodejs
       state: present

    - name: Copy Backend service
      ansible.builtin.copy:
       src: backend.service
       dest: /etc/systemd/system/backend.service

    - name: Creating user
      ansible.builtin.user:
       name: expense
    
    - name: Deleting old app content
      ansible.builtin.file:
       name: /app
       state: absent

    - name: Creating directory
      ansible.builtin.file:
       name: /app
       state: directory

    - name: Downloading and extracting app content
      ansible.builtin.unarchive:
       src: https://expense-artifacts.s3.amazonaws.com/backend.zip 
       dest: /app
       remote_src: yes

    - name:  Download nodejs dependencies
      ansible.builtin.shell: npm install
       args:
        chdir: /app

    - name: Installing Mysql client
      ansible.builtin.dnf:
       name: mysql
       state: present
     
    - name: Load the schema
      ansible.builtin.shell: mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql 

    - name: Starting backend service
      ansible.builtin.systemd:
       name: backend
       state: restarted
       enabled: yes
       daemon-reload: yes

    

