- name: Disabling Mysql default version
  ansible.builtin.shell: dnf module disable mysql -y

- name: Creating Mysql repo
  ansible.builtin.copy:
   src: mysql.repo
   dest: /etc/yum.repos.d/mysql.repo

- name: Installing mysql community server
  ansible.builtin.dnf:
   name: mysql-community-server -y
   state: present

- name: Strating mysql server
  ansible.builtin.systemd:
   name: mysqld
   state: restarted
   enabled: yes

- name: Setup  Password 
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{MYSQL_ROOT_PASSWORD}}
